### ISSUE TITLE
Unable to proof per Induction over Nat with Lists

### ISSUE THREAD

**Issue by LeanderK** [RyanGlScott/eliminators#3]
I am trying to proof the following:

```haskell
type WhyDomainMatches a b (n :: Nat)
     = ToDomain (Replicate n (a -> b)) :~: Replicate n a
```
where
```haskell
type family ToDomain (xs :: [Type]) :: [Type] where
    ToDomain '[] = '[];
    ToDomain ((a -> b) ': r) = a ': ToDomain r
```
(Replicate is the usual Replicate form the singletons prelude)
through
```haskell
domainMatches :: forall (n :: Nat) (a :: Type) (b :: Type). SingI n => ToDomain (Replicate n (a -> b)) :~: Replicate n a
domainMatches = elimNat @(WhyDomainMatchesSym2 a b) @n (sing @Nat @n) base step
            where
                base :: WhyDomainMatches a b 0
                base = Refl
        
                step :: forall (k :: Nat). 
                    Sing k 
                    -> WhyDomainMatches a b k 
                    -> WhyDomainMatches a b (k :+ 1)
                step _ = cong @_ @_ @((:$$) a)
```
I think that in theory this should work, `cong` is copied from your tests, but GHC is not convinced yet.
```haskell
Could not deduce: ToDomain
                          (Data.Singletons.Prelude.List.Case_6989586621679725646
                             (k GHC.TypeNats.+ 1)
                             (a -> b)
                             (GHC.TypeNats.EqNat (k GHC.TypeNats.+ 1) 0))
                        ~
                        (a : ToDomain
                               (Data.Singletons.Prelude.List.Case_6989586621679725646
                                  k (a -> b) (GHC.TypeNats.EqNat k 0)))
```
I've added `(z :: Nat). (SingI n, (ToDomain (Replicate (z :+ 1) (a -> b)) ~ (a : ToDomain (Replicate (z) (a -> b)))))` to the constraints of domainMatches, but it didn't help, so I've also added it to step, but now I've got an error I can't really interpret:
```haskell
Could not deduce: ToDomain
                          (Data.Singletons.Prelude.List.Case_6989586621679725646
                             (k GHC.TypeNats.+ 1)
                             (a -> b)
                             (GHC.TypeNats.EqNat (k GHC.TypeNats.+ 1) 0))
                        ~
                        (a : ToDomain
                               (Data.Singletons.Prelude.List.Case_6989586621679725646
                                  n (a -> b) (GHC.TypeNats.EqNat n 0)))
        arising from a use of ‘step’
``` 
(why should k +1 equal n? There must be something wrong with my code!).
I've also got a second question, more fundamental. Assuming I get this to compile, how can I actually use this?
Also, cong & friends seem really useful and fundamental after a bit of searching, why are they not exported? They make the codebase pretty scary (I don't really understand what's going on), I think the actual Induction is surprisingly straightforward if you are familiar with the concept.

**Comment by RyanGlScott** [comment]
I don't think there's anything conceptually wrong with your code. I think the real culprit is that you're trying to use `GHC.TypeLits.Nat` to prove this. The reason being that `Nat` isn't an inductive data type, and as such, GHC can't figure out many things that would otherwise be simple. (I'd go as far to call `Nat` an ugly hack that GHC only added so you could write numeric literals at the type level.)

Admittedly, I did advertise `elimNat` as a cute trick to treat `Nat` inductively. And for certain things, this claim holds water, but I don't think you're going to be able to get away with it here.

If you look at the [definition of `replicate`](https://github.com/goldfirere/singletons/blob/30325dae48a8bd836b39a93f36505e9c1f62f6f7/src/Data/Singletons/Prelude/List.hs#L764-L765) in `singletons`, perhaps you'll get a better idea of why GHC is having trouble proving your claim:

```haskell
-- Functions working on infinite lists don't promote because they create
-- infinite types. replicate also uses integers, but luckily it can be rewritten
-- ...
  replicate               :: Nat -> a -> [a]
  replicate n x           = if n == 0 then [] else x : replicate (n-1) x
```

As a result, the type-level `Replicate n` gets stuck on any `n` that isn't statically known to be `0`, `1`, or some other concrete literal. Sad news.

My advice: don't give yourself any more `Nat` headaches if you can avoid. Just switch to proper inductive natural number definition:

```haskell
$(singletons
  [d| data Peano = Zero | Succ Peano

      replicate :: Peano -> a -> [a]
      replicate Zero     _ = []
      replicate (Succ n) x = x : replicate n x
    |])
```

And your proof will go through a _lot_ more smoothly:

**Comment by LeanderK** [comment]
Hmm. Is there a way to use the isomorphism between the representations to prove this? I can't use Peano-Types directly, I rely on fast integers and the list can also get quite long. I still don't understand this fully. I would assume that adding `(ToDomain (Replicate (z :+ 1) (a -> b)) ~ (a : ToDomain (Replicate (z) (a -> b))))` to step would solve the problem for Step.
Also, I am still not sure how to actually use the proof once it's working.

**Comment by RyanGlScott** [comment]
> Hmm. Is there a way to use the isomorphism between the representations to prove this?

I'm not sure which isomorphism you're referring to here. (You can hand-wave and say "of course `Nat` and `Peano` are obviously isomorphic, but we need something to convince GHC of this fact. This proves to be trickier than you might expect.)

> I rely on fast integers for other operations.

OK. This isn't an all-or-nothing scenario—it's possible to use both `Nat`s and `Peano`s in the same program, using these conversion functions:

```haskell
$(singletons
  [d| data Peano = Zero | Succ Peano

      fromNat :: Nat -> Peano
      fromNat n | n  < 0 = error "fromNat n | n < 0"
                | n == 0 = Zero
                | n  > 0 = Succ (fromNat (n-1))

      toNat :: Peano -> Nat
      toNat Zero = 0
      toNat (Succ n) = 1 + toNat n
    |])
```

(Perhaps this is the "isomorphism" you were referring to earlier?)

> Also, I am still not sure how to actually use the proof once it's working.

I'm not sure what you mean. `doaminMatches` is a function like any other—just give it the arguments it expects, and it'll do its thing.

> Can i unsafecoerce something like this? 😀 I know this kinda defeats the purpose, but I am still in the experimenting-phase and the code I want to write doesn't compile yet.

Sure, it's quite common to see `Nat`-heavy code assume a bunch of axioms about `Nat` using the following utility function:

```haskell
axiom :: a :~: b
axiom = unsafeCoerce Refl

myHardToProveFact :: Foo :~: Bar
myHardToProveFact = axiom
```

Of course, this assumes that you, the smart programmer, can show that this axiom holds, so use this with caution.

**Comment by LeanderK** [comment]
> I'm not sure which isomorphism you're referring to here. (You can hand-wave and say "of course Nat and Peano are obviously isomorphic, but we need something to convince GHC of this fact. This proves to be trickier than you might expect.)
I should have formulated this in a more clear way, but this is what I thought of. I am a bit new to all this, but it seemed like a pretty straightforward thing in my mind. 
> I'm not sure what you mean. doaminMatches is a function like any other—just give it the arguments it expects, and it'll do its thing.
Well, I have a function where ` ToDomain (Replicate n (a -> b)) ~ Replicate n a` could not get deduced by the compiler. If I understood it right I am building a proof, but I am not sure what the relationship between `~` and ':~:` actually is, do I have to singletonize the proof again? I have to use it somehow.

I actually encountered the Nat axioms today, so I could just write them all down right now 😉 (well, they are not hard either) I can't image that this would solve my problem though.

**Comment by RyanGlScott** [comment]
Let's motivate a use of `axiom` by using it to complete your proof. You're getting stuck because GHC can't conclude the following fact:

```haskell
replicateSucc :: forall k a. Replicate (k :+ 1) a :~: (a : Replicate k a)
```

Again, this would be dead simple if `k` were an inhabitant of actual inductive data type. But `Nat` is not such a type, and the definition of `Replicate` makes it so that it's not particularly amenable to inductive reasoning. So one way you could admit this fact it to use `axiom`:

```haskell
replicateSucc :: forall k a. Replicate (k :+ 1) a :~: (a : Replicate k a)
replicateSucc = axiom
```

Now the `step` case of `domainMatches` simply becomes:

```haskell
                step _ = case replicateSucc @k @(a -> b) of
                           Refl -> case replicateSucc @k @a of
                             Refl -> cong @_ @_ @((:$$) a)
```

Perhaps there's a way to define `replicateSucc` without having to resort to `axiom`. But if there is, I'm nowhere near smart enough to figure it out ;)

**Comment by LeanderK** [comment]
Thank you. 
Short question (I know it's offtopic, feel free to give me feedback to not misuse these issues).
What is the best way to convince the type-checker of implications, like `OnlyFunctions (a: as) => a ~ (x -> y)`?

**Comment by RyanGlScott** [comment]
> What is the best way to convince the type-checker of implications, like `OnlyFunctions (a: as) => a ~ (x -> y)`?

When you say "convince", do you mean in a global sense? As in convincing GHC to always use `OnlyFunctions (a: as) => a ~ (x -> y)` when solving constraints? If so, that isn't currently possible. (Short of a GHC typechecker plugin like [`ghc-typelits-natnormalise`](http://hackage.haskell.org/package/ghc-typelits-natnormalise), but I wouldn't recommend implementing it this way unless you're a glutton for pain ;) ).

If you mean in a local sense (as in convincing GHC to use `OnlyFunctions (a: as) => a ~ (x -> y)` in some particular scope), then the most straightforward way to conjure up an axiom `cleverNameHere :: OnlyFunctions (a: as) => a :~: (x -> y)` and pattern-match on it, similarly to what is done in https://github.com/RyanGlScott/eliminators/issues/3#issuecomment-337239663.

**Comment by LeanderK** [comment]
Well, that's pretty straightforward, I could have thought of that 🙂
A local scope is fine.
This raises of course more questions (Why would a type-checker plugin be so bad? Isn't this use-case exactly where they would shine? I imagine doing it the proper way in GHC to take a long time before it arrives in the users code, also I expect working on GHC to be difficult...)
Thank you!

**Comment by RyanGlScott** [comment]
FWIW, I asked some of the folks who work on the `ghc-typelits-natnormalise` typechecker plugin if it would be possible to give GHC the power to typecheck a function like `replicateSucc` above. They didn't answer with a definitive "no", but it definitely seems like it's trickier than one would expect: https://github.com/clash-lang/ghc-typelits-natnormalise/issues/13

**Comment by LeanderK** [comment]
I just read your blogpost about quantified contexts and wondered whether this could help here:
Is something like this possible?
```haskell
forall k. KnownNat k => (k + 1 :/~: 0)
```
where 
`:/~:` is not equal (is something like this existing?)

**Comment by RyanGlScott** [comment]
Nope—GHC has no notion of "inequality constraints".

**Comment by LeanderK** [comment]
that's unfortunate...I bet there's a reason

**Comment by RyanGlScott** [comment]
The most straightforward answer for why there's no inequality constraints is because GHC's type system is based off of intuitionistic logic, where the law of excluded middle (i.e., every proposition is either true or false) does not hold. In intuitionistic logic, every proposition is either provable, or assuming it would lead to a contradiction. In other words:

```haskell
Either a (a -> Void)
```

This is a trick that I use a lot in the `eliminators` library—e.g., [here](https://github.com/RyanGlScott/eliminators/blob/6032dbd5bbb9d5764a0a4ae24965a30ef337fe88/tests/DecideTypes.hs#L56). But before you ask, this trick won't work for `GHC.TypeNats.Nat`, since GHC doesn't have the ability to tell that `n` and `n + 1` are apart, since `(+)` is not inductively defined.

**Comment by LeanderK** [comment]
This is really confusing! 😀
I have take some time and read what that really means...
